const mongoose = require('mongoose');

const dataSchema = new mongoose.Schema({

  // booking_number:String,
  // account_code:String,
  // po_number:String,
  // subject:String,
  // description:String,
  // case_owner:String,
  // category:String,
  // sub_category:String,
  // priority:String,
  // case_id:String

  booking_number:String, 
  account_code:String, 
  po_number:String,
  case_number:String, 
  subject:String, 
  description:String, 
  case_owner:String, 
  category:String,
  sub_category:String,
  priority:String,
  notes:String,
  root_cause_description:String,
  root_cause_category:String,
  resolution_description:String,
  resolution_category:String,
  case_closed:String,
  transaction_nbr:String,
  master_customer_code:String,
  customer_code:String,
  account_name:String,
  consignee_b_l:String,
  notification_persion_1:String,
  notification_party1_address_line_1:String,
  notification_party1_address_line_2:String,
  notification_party1_address_line_3:String,
  origin_port:String,
  origin_country:String,
  all_document_received_flag:String,
  inco_term_booking:String,
  export_country_name:String,
  vendor_name:String,
  shipper:String,
  destination_country:String,
  discharge_post_bl:String,
  final_destination_bl:String,
  load_post:String,
  transport_mode:String,
  service_type:String,
  load_type:String,
  shipment_type_code:String,
  shipment_type:String,
  apll_program_indicator:String,
  booked_date:String,
  mode:String,
  incoterm:String,
  container_number:String,
  bl_number:String,
  fcr_number:String,
  shipper_name:String,
  shipper_code:String,
  vessel_name:String,
  voyage_number:String,
  carrier_code:String,
  destination_port:String,
  booking_status:String,
  shipment_status:String,
  latest_event:String,
  si_cutoff_date:String,
  si_timeliness:String,
  si_triggered_user:String,
  si_error:String,
  asn_send_date:String,
  asn_triggered_user:String,
  asn_error:String,
  estimated_departure_date:String,
  actual_departure_date:String,
  estimated_arrival_date:String,
  actual_arrival_date:String,
});

const DataModel = mongoose.model('crm-dbs', dataSchema);


module.exports = DataModel;
